name: DEV Workflow

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

  deploy:
    name: deploy
    
    runs-on: ubuntu-latest
    needs: build
    environment: 
        name: dev
    steps:
      - name: Create Manual Approval Issue
        uses: Niladri579/github-actions-example@v1
        with:
   
          label: approval
    
          title: optional, default is [Github Actions] Manual Approval Required
    # Body to assign to the issue
          body:  optional, default is Closing this issue will approve all changes listed in comments to the next stage
    # The gitHub token used to create an authenticated client
          github-token: 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

  store-artifact:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Store artifact
        run: echo "Hello World!"
